export const mockData = [
  {
    id: 1,
    name: "Autumn Jacket",
    title: "Men's Autumn Jacket with Hood",
    price: 59.99,
    image: "https://images.pexels.com/photos/5792896/pexels-photo-5792896.jpeg",
    category: "men",
  },
  {
    id: 2,
    name: "Trendy Duo Outfit",
    title: "Children's Fashionable Couple Casual Wear",
    price: 44.99,
    image: "https://images.pexels.com/photos/1620765/pexels-photo-1620765.jpeg",
    category: "kids",
  },
  {
    id: 3,
    name: "Casual Group Style",
    title: "Fashionable Men and Women Streetwear",
    price: 69.99,
    image: "https://images.pexels.com/photos/7081105/pexels-photo-7081105.jpeg",
    category: "men",
  },
  {
    id: 4,
    name: "Traditional Family Dress",
    title: "Traditional Wear for Woman and Girl",
    price: 39.99,
    image: "https://images.pexels.com/photos/8819201/pexels-photo-8819201.jpeg",
    category: "women",
  },
  {
    id: 5,
    name: "Urban Streetwear",
    title: "Men's Black Urban Street Style Outfit",
    price: 49.99,
    image: "https://images.pexels.com/photos/2209971/pexels-photo-2209971.jpeg",
    category: "men",
  },
  {
    id: 6,
    name: "Pink Floral Dress",
    title: "Women's Pink Floral Summer Dress",
    price: 34.99,
    image: "https://images.pexels.com/photos/6311601/pexels-photo-6311601.jpeg",
    category: "women",
  },
  {
    id: 7,
    name: "Boys Fashion Hoodie",
    title: "Boys' Hooded Sweatshirt and Pants Set",
    price: 27.99,
    image: "https://images.pexels.com/photos/3662832/pexels-photo-3662832.jpeg",
    category: "kids",
  },
  {
    id: 8,
    name: "Beige Winter Coat",
    title: "Women's Elegant Beige Winter Coat",
    price: 74.99,
    image: "https://images.pexels.com/photos/1916825/pexels-photo-1916825.jpeg",
    category: "women",
  },
  {
    id: 9,
    name: "Kids Denim Dungaree",
    title: "Little Girl's Blue Denim Dungaree",
    price: 24.49,
    image: "https://images.pexels.com/photos/1648377/pexels-photo-1648377.jpeg",
    category: "kids",
  },
  {
    id: 10,
    name: "Grey Blazer",
    title: "Men's Grey Slim Fit Office Blazer",
    price: 89.99,
    image: "https://images.pexels.com/photos/3771836/pexels-photo-3771836.jpeg",
    category: "men",
  },
  {
    id: 11,
    name: "Modern Sari Look",
    title: "Women's Festive Sari with Modern Twist",
    price: 56.0,
    image: "https://images.pexels.com/photos/1689731/pexels-photo-1689731.jpeg",
    category: "women",
  },
  {
    id: 12,
    name: "Casual Day Out",
    title: "Women's Day Out Look with Backpack",
    price: 32.0,
    image: "https://images.pexels.com/photos/3756168/pexels-photo-3756168.jpeg",
    category: "women",
  },
  {
    id: 13,
    name: "Monochrome Casual",
    title: "Men's Black & White Monochrome Outfit",
    price: 52.99,
    image: "https://tinyurl.com/monocasual",
    category: "men",
  },
  {
    id: 14,
    name: "Ethnic Kidswear",
    title: "Boys Traditional Ethnic Wear",
    price: 35.75,
    image: "https://images.pexels.com/photos/1648378/pexels-photo-1648378.jpeg",
    category: "kids",
  },
  {
    id: 15,
    name: "Leather Jacket",
    title: "Men's Black Leather Biker Jacket",
    price: 119.99,
    image: "https://images.pexels.com/photos/336372/pexels-photo-336372.jpeg",
    category: "men",
  },
  {
    id: 16,
    name: "Retro Polka Dress",
    title: "Women's Retro Polka Dot Summer Dress",
    price: 44.0,
    image: "https://images.pexels.com/photos/1394882/pexels-photo-1394882.jpeg",
    category: "women",
  },
  {
    id: 17,
    name: "Teen Girl Fashion",
    title: "Teen Girl in Plaid Skirt Outfit",
    price: 38.0,
    image: "https://images.pexels.com/photos/3763188/pexels-photo-3763188.jpeg",
    category: "kids",
  },
  {
    id: 18,
    name: "Winter Beanie Look",
    title: "Men's Winter Look with Beanie and Jacket",
    price: 66.0,
    image: "https://images.pexels.com/photos/1648468/pexels-photo-1648468.jpeg",
    category: "men",
  },
  {
    id: 19,
    name: "Kids Pajama Set",
    title: "Cute Girl's Printed Pajama Nightwear Set",
    price: 20.0,
    image: "https://images.pexels.com/photos/1648375/pexels-photo-1648375.jpeg",
    category: "kids",
  },
  {
    id: 20,
    name: "Teen Boy Casuals",
    title: "Teen Boy’s Casual Tee and Shorts Set",
    price: 25.0,
    image: "https://images.pexels.com/photos/1619653/pexels-photo-1619653.jpeg",
    category: "kids",
  },
  {
    id: 21,
    name: "Boho Girl Style",
    title: "Bohemian Fashion Style for Women",
    price: 58.5,
    image: "https://images.pexels.com/photos/1120473/pexels-photo-1120473.jpeg",
    category: "women",
  },
];
